development:
  clients:
    default:
      database: parking_development
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost' %>:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: parking_test
      hosts:
        - <%= ENV['MONGO_HOST'] || 'localhost' %>:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
